### ISSUE TITLE
Should we update contact information?

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust-log-analyzer#39]
Currently, we suggest contacting Tim on the comments:

https://github.com/rust-lang/rust-log-analyzer/blob/1d8e2feac5480c63ad9a5c7d4dfd733f46b7eca1/src/bin/server/worker.rs#L255

But they already not belong to the infra team so we should update the information. There may be few people to contact them though.

cc: @pietroalbini

**Comment by pietroalbini** [comment]
Thanks! Pushed a commit to update the contact information!
